#
# Package name
#

NAME=RNMath



#
# List of source files
#

CCSRCS=$(NAME).cpp \
  RNPolynomial.cpp RNAlgebraic.cpp RNEquation.cpp RNSystemOfEquations.cpp \
  RNDenseLUMatrix.cpp RNDenseMatrix.cpp RNMatrix.cpp \
  RNVector.cpp


#
# Dependencies
#

PKG_DEPENDENCIES = RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs



