#
# Application name and list of source files.
#

NAME=conf2overlap
CCSRCS=$(NAME).cpp 



#
# Dependency libraries
#

PKG_LIBS=-lRGBD -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


