#
# Package name
#

NAME=R3Surfels



#
# List of source files
#

CCSRCS=$(NAME).cpp \
  R3Surfel.cpp \
  R3SurfelBlock.cpp \
  R3SurfelDatabase.cpp \
  R3SurfelConstraint.cpp \
  R3SurfelPoint.cpp \
  R3SurfelPointSet.cpp \
  R3SurfelPointGraph.cpp \
  R3SurfelNode.cpp \
  R3SurfelNodeSet.cpp \
  R3SurfelTree.cpp \
  R3SurfelScan.cpp \
  R3SurfelFeature.cpp \
  R3SurfelFeatureSet.cpp \
  R3SurfelFeatureVector.cpp \
  R3SurfelFeatureEvaluation.cpp \
  R3SurfelObject.cpp \
  R3SurfelObjectSet.cpp \
  R3SurfelObjectProperty.cpp \
  R3SurfelObjectRelationship.cpp \
  R3SurfelLabel.cpp \
  R3SurfelLabelSet.cpp \
  R3SurfelLabelProperty.cpp \
  R3SurfelLabelRelationship.cpp \
  R3SurfelLabelAssignment.cpp \
  R3SurfelScene.cpp \
  R3SurfelUtils.cpp


#
# Dependencies
#

PKG_DEPENDENCIES = R3Shapes R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs









