#
# Application name 
#

NAME=grdview



#
# Source files.
#

CCSRCS=$(NAME).cpp



#
# Libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lfglut -ljpeg -lpng



#
# Include standard makefile
#

include ../../makefiles/Makefile.apps

