#
# Application name 
#

NAME=pdbview



#
# Source files.
#

CCSRCS=$(NAME).cpp



#
# Libraries
#

PKG_LIBS=-lPDB -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng



#
# Include standard makefile
#

include ../../makefiles/Makefile.apps

