#
# Application name and list of source files.
#

NAME=sflview
CCSRCS=$(NAME).cpp R3SurfelViewer.cpp debug.cpp align.cpp map.cpp 



#
# Dependency libraries
#

PKG_LIBS=-lR3Surfels -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


