#
# Application name and list of source files.
#

NAME=scn2cam
CCSRCS=$(NAME).cpp 


#
# Dependency libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps



