#
# Application name and list of source files.
#

NAME=sfl2sfl
CCSRCS=$(NAME).cpp



#
# Dependency libraries
#

PKG_LIBS=-lR3Surfels -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


