#
# Application name and list of source files.
#

NAME=pfmview
CCSRCS=$(NAME).cpp 



#
# Dependency libraries
#

PKG_LIBS=-lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


