#
# Package name 
#

NAME=PDB



#
# List of source files
#

CCSRCS=$(NAME).cpp \
	PDBElement.cpp PDBAminoAcid.cpp \
        PDBAtom.cpp PDBResidue.cpp PDBChain.cpp PDBModel.cpp PDBFile.cpp \
        PDBBond.cpp PDBAtomTypes.cpp PDBUtil.cpp PDBDistance.cpp



#
# Dependencies
#

PKG_DEPENDENCIES = R3Shapes R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs



