#
# Application name 
#

NAME=msh2grd



#
# Source files
#

CCSRCS=$(NAME).cpp 



#
# Libraries
#

PKG_LIBS=-lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng



#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















